### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by tomtau**

### CODE REVIEW

**Comment by wigy-opensource-developer** [comment]
@maciejhirsz I see the paritytech fork has a conflicting commit on their master: https://github.com/maciejhirsz/tiny-bip39/compare/master...paritytech:master

Could you please update us on the maintenance status of this repository? I also see the 2 conflicting zeroize PRs that are not merged into master and there has not been a release recently. Will you delegate maintenance to Parity or will you keep this repo alive?

**Comment by maciejhirsz** [comment]
@wigy-opensource-developer I've fixed my notifications game some two weeks ago, I should be more prompt on merging PRs in the future.

**Comment by maciejhirsz** [comment]
This is now published in 0.8.0.

**Comment by wigy-opensource-developer** [comment]
Awesome. Thanks for your efforts.

**Pull request merged**
